language: csharp
solution: CellWars.Async.sln
matrix:
  include:
    - dotnet: 2.1.502
      mono: none
      install:
        - dotnet restore
      script:
        - dotnet build
        - dotnet test test/CellWars.Async.Tests/CellWars.Async.Tests.csproj
    - mono: latest