language: csharp
solution: CellWars.Threading.sln
matrix:
  include:
    - dotnet: 2.1.502
      mono: none
      install:
        - dotnet restore
      script:
        - dotnet build
        - dotnet test test/CellWars.Threading.Tests/CellWars.Threading.Tests.csproj
    - mono: latest