language: csharp
solution: CellWars.Async.sln
matrix:
  include:
    - dotnet: 2.1.502
      mono: none
      install:
        - dotnet restore
      script:
        - dotnet build
        - dotnet test test/CellWars.Async.Tests/CellWars.Async.Tests.csproj
    - mono: latest
      install:
        - nuget restore solution-name.sln
        - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
      script:
        - msbuild /p:Configuration=Release CellWars.Async.Tests.sln
        - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./MyProject.Tests/bin/Release/CellWars.Async.Tests.dll