language: csharp
solution: CellWars.Async.sln
matrix:
  include:
    - dotnet: 2.1.502
      mono: none
      install:
        - dotnet restore
      script:
        - dotnet build
        - dotnet test test/CellWars.Async.Tests/CellWars.Async.Tests.csproj
    - mono: latest
      install:
        - nuget restore test/CellWars.Async.Tests/CellWars.Async.Tests.csproj
        - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
      script:
        - nuget restore test/CellWars.Async.Tests/CellWars.Async.Tests.csproj
        - msbuild /p:Configuration=Release test/CellWars.Async.Tests/CellWars.Async.Tests.csproj
        - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./test/CellWars.Async.Tests/bin/Release/CellWars.Async.Tests.dll
